apiVersion: apps/v1
kind: Deployment
metadata:
  name: calmify-deployment
  labels:
    app: calmify
spec:
  replicas: 2
  selector:
    matchLabels:
      app: calmify
  template:
    metadata:
      labels:
        app: calmify
    spec:
      containers:
        - name: calmify
          image: ghcr.io/sumanth12-afk/calmify_mental_wellness_reimagined:latest
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "production"
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 20
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: calmify-service
spec:
  type: ClusterIP
  selector:
    app: calmify
  ports:
    - port: 80
      targetPort: 3000
