name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  IMAGE_NAME: ghcr.io/${{ github.repository }}
  IMAGE_TAG: latest
  IMAGE_NAME_LOWER: ghcr.io/${{ github.repository }}

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

      - name: Run unit tests
        run: npm test

  sonarqube:
    needs: lint-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Run SonarQube scan
        uses: SonarSource/sonarqube-scan-action@v5.0.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=Sumanth12-afk_Calmify_Mental_Wellness_Reimagined
            -Dsonar.organization=sumanth12-afk
            -Dsonar.sources=.
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info

  build-and-push:
    needs: sonarqube
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Normalize image name to lowercase
        run: echo "IMAGE_NAME_LOWER=$(echo $IMAGE_NAME_LOWER | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Log in to GHCR
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        run: docker build -t $IMAGE_NAME_LOWER:$IMAGE_TAG .

      - name: Push Docker image
        run: docker push $IMAGE_NAME_LOWER:$IMAGE_TAG

  trivy-scan:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Normalize image name to lowercase
        run: echo "IMAGE_NAME_LOWER=$(echo $IMAGE_NAME_LOWER | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Log in to GHCR
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install wget apt-transport-https gnupg lsb-release -y
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install trivy -y

      - name: Scan Docker image with Trivy
        run: trivy image --exit-code 0 --severity HIGH,CRITICAL --format table --output trivy-report.txt $IMAGE_NAME_LOWER:$IMAGE_TAG

      - name: Upload Trivy Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: trivy-report
          path: trivy-report.txt

  deploy:
    needs: trivy-scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Install KinD
        uses: helm/kind-action@v1.8.0
        with:
          version: v0.20.0

      - name: Create KinD cluster
        run: kind create cluster --wait 60s

      - name: Set image name
        run: echo "CALMIFY_IMAGE=ghcr.io/sumanth12-afk/calmify_mental_wellness_reimagined:latest" >> $GITHUB_ENV

      - name: Log in to GHCR
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Pull image from GHCR
        run: docker pull $CALMIFY_IMAGE

      - name: Load image into KinD
        run: kind load docker-image $CALMIFY_IMAGE

      - name: Get cluster info
        run: |
          kubectl cluster-info
          kubectl get nodes

      - name: Validate manifests
        run: kubectl apply --dry-run=client -f k8s/deployment.yaml

      - name: Deploy to Kubernetes
        run: kubectl apply -f k8s/deployment.yaml

      - name: Wait for rollout
        run: kubectl rollout status deployment/calmify-deployment

      - name: Debug deployment issues
        if: failure()
        run: |
          echo "🔍 Checking pod statuses..."
          kubectl get pods -o wide

          echo "📦 Describing pods..."
          kubectl describe pods || echo "❌ Failed to describe pods"

          echo "📝 Trying to fetch logs from the first pod..."
          POD_NAME=$(kubectl get pods -o jsonpath="{.items[0].metadata.name}")
          if [ -n "$POD_NAME" ]; then
            echo "Fetching logs from pod: $POD_NAME"
            kubectl logs "$POD_NAME"
          else
            echo "❌ No pods found to fetch logs from"
          fi
